# Generated by Django 4.2.2 on 2023-06-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_veune_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='veune_image',
            new_name='image',
        ),
    ]
