# Generated by Django 4.2.2 on 2023-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_veune_image_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
